name: Scrape V2Ray Links

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Determine current file
      id: current_file
      run: |
        # Determine the current file based on the timestamp
        CURRENT_TIME=$(date +%s)
        HOURS_PASSED=$((CURRENT_TIME / 3600 % 24))
        if [ $((HOURS_PASSED / 12 % 2)) -eq 0 ]; then
          echo "file=v2tel_links1.txt" >> $GITHUB_ENV
          echo "next_file=v2tel_links2.txt" >> $GITHUB_ENV
        else
          echo "file=v2tel_links2.txt" >> $GITHUB_ENV
          echo "next_file=v2tel_links1.txt" >> $GITHUB_ENV
        fi

    - name: Run scraping script for the determined file
      run: |
        python main.py ${{ env.file }}

    - name: Delete the previous file after 12 hours
      if: ${{ github.event_name == 'schedule' && github.run_number % 72 == 0 }} # Deletes every 12 hours (72 10-minute intervals)
      run: |
        echo "Deleting the previous file: ${{ env.next_file }}"
        rm -f ${{ env.next_file }}

    - name: Commit and push changes
      env:
        PROV2: ${{ secrets.PROV2 }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add ${{ env.file }}
        git commit -m "Update V2Ray links"
        git push https://x-access-token:${PROV2}@github.com/${{ github.repository }}.git HEAD:main




