name: Scheduled Push Workflow

on:
  schedule:
    - cron: '*/10 * * * *'  # This will trigger the workflow every 10 minutes

jobs:
  push_code:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update links (optional)
      run: |
        echo "Update the links "

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Updated links at  $(date)"
        git push
