name: Scrape V2Ray Links

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run scraping script
      run: |
        python main.py  

    - name: Commit and push changes
      env:
        PROV2: ${{ secrets.PROV2 }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add v2tel_link.txt
        git commit -m "Update V2Ray links"
        git push https://x-access-token:${PROV2}@github.com/${{ github.repository }}.git HEAD:main

